#!/usr/bin/env python3
"""
Linux Module Injector
Injects kernel modules into initramfs before boot
"""

import json
from pathlib import Path
import subprocess

class LinuxInjector:
    def __init__(self):
        self.base_dir = Path(__file__).parent.parent
        self.hardware_profile = self.load_hardware()
        self.manifest = self.load_manifest()
        self.archive_dir = self.base_dir / "DriverArchive"
    
    def load_hardware(self):
        """Load hardware profile"""
        profile_file = self.base_dir / "HardwareProfiles" / "current.json"
        if profile_file.exists():
            with open(profile_file, 'r') as f:
                return json.load(f)
        return {}
    
    def load_manifest(self):
        """Load driver manifest"""
        manifest_file = self.base_dir / "HardwareProfiles" / "current_manifest.json"
        if manifest_file.exists():
            with open(manifest_file, 'r') as f:
                return json.load(f)
        return {}
    
    def get_required_modules(self, computer_type):
        """Get modules needed based on computer type"""
        modules = self.manifest.get('linux', {}).get('modules', [])
        
        if computer_type in ['INTEL_PC', 'AMD_PC']:
            archive_path = "Linux/x86_Common"
        elif computer_type == 'INTEL_MAC':
            archive_path = "Linux/Mac_Specific"
        elif computer_type == 'ARM_MAC':
            archive_path = "Linux/Asahi"
        else:
            archive_path = "Linux/x86_Common"
        
        return modules, archive_path
    
    def check_system_modules(self, required_modules):
        """Check which modules exist on system"""
        found = []
        missing = []
        
        # Check in /lib/modules/
        modules_dir = Path("/lib/modules")
        if modules_dir.exists():
            for module_name in required_modules:
                # Search for module
                matches = list(modules_dir.rglob(f"{module_name}.ko*"))
                if matches:
                    found.append((module_name, matches[0]))
                else:
                    missing.append(module_name)
        
        return found, missing
    
    def inject_linux_modules(self, computer_type):
        """Main injection function"""
        print("=" * 60)
        print("🐧 Linux Module Injector")
        print("=" * 60)
        
        print(f"\n💻 Computer Type: {computer_type}")
        
        # Get required modules
        required, archive_path = self.get_required_modules(computer_type)
        print(f"\n📋 Required Modules: {len(required)}")
        for module in required:
            print(f"   - {module}")
        
        # Check system modules
        found, missing = self.check_system_modules(required)
        
        print(f"\n✅ Available on System: {len(found)}/{len(required)}")
        for module_name, module_path in found:
            print(f"   ✅ {module_name}")
        
        if missing:
            print(f"\n⚠️  Missing: {len(missing)}")
            for module in missing:
                print(f"   ❌ {module}")
        
        # Generate module loading config
        print(f"\n🔧 Generating module configuration...")
        
        modules_load_file = Path("/tmp/universal_modules.conf")
        with open(modules_load_file, 'w') as f:
            f.write("# Auto-generated by Universal MultiBoot\n")
            f.write("# Modules to load at boot\n\n")
            for module_name, _ in found:
                f.write(f"{module_name}\n")
        
        print(f"✅ Module config: {modules_load_file}")
        
        print("\n" + "=" * 60)
        print("�� Integration Instructions:")
        print("=" * 60)
        print("1. Copy to /etc/modules-load.d/:")
        print(f"   sudo cp {modules_load_file} /etc/modules-load.d/universal.conf")
        print("2. Update initramfs:")
        print("   sudo update-initramfs -u")
        print("3. Reboot")
        print("=" * 60)
        
        return True

def main():
    """Test the injector"""
    injector = LinuxInjector()
    
    # Detect computer type
    computer_type = injector.hardware_profile.get('platform', 'INTEL_PC')
    if computer_type == 'Intel':
        computer_type = 'INTEL_PC'
    elif computer_type == 'AMD':
        computer_type = 'AMD_PC'
    
    # Run injection
    injector.inject_linux_modules(computer_type)

if __name__ == "__main__":
    main()
