#!/usr/bin/env python3
"""
Windows Driver Injector
Injects drivers into Windows before boot
"""

import json
from pathlib import Path
import shutil

class WindowsInjector:
    def __init__(self):
        self.base_dir = Path(__file__).parent.parent
        self.hardware_profile = self.load_hardware()
        self.manifest = self.load_manifest()
        self.archive_dir = self.base_dir / "DriverArchive"
    
    def load_hardware(self):
        """Load hardware profile"""
        profile_file = self.base_dir / "HardwareProfiles" / "current.json"
        if profile_file.exists():
            with open(profile_file, 'r') as f:
                return json.load(f)
        return {}
    
    def load_manifest(self):
        """Load driver manifest"""
        manifest_file = self.base_dir / "HardwareProfiles" / "current_manifest.json"
        if manifest_file.exists():
            with open(manifest_file, 'r') as f:
                return json.load(f)
        return {}
    
    def get_required_drivers(self, computer_type):
        """Get drivers needed based on computer type"""
        drivers = self.manifest.get('windows', {}).get('drivers', [])
        
        if computer_type in ['INTEL_PC', 'AMD_PC']:
            # PC - needs PC drivers
            archive_path = "Windows/PC_Drivers"
        elif computer_type == 'INTEL_MAC':
            # Intel Mac - needs Boot Camp drivers
            archive_path = "Windows/BootCamp_Drivers"
        elif computer_type == 'ARM_MAC':
            # ARM Mac - needs ARM drivers
            archive_path = "Windows/ARM_Drivers"
        else:
            archive_path = "Windows/PC_Drivers"
        
        return drivers, archive_path
    
    def find_drivers_in_archive(self, archive_path):
        """Find driver files in archive"""
        found = []
        search_dir = self.archive_dir / archive_path
        
        if search_dir.exists():
            # Find all driver files
            found.extend(search_dir.rglob("*.exe"))
            found.extend(search_dir.rglob("*.inf"))
            found.extend(search_dir.rglob("*.sys"))
            found.extend(search_dir.rglob("*.dll"))
        
        return found
    
    def create_driver_install_script(self, drivers, windows_mount):
        """Create batch script to install drivers in Windows"""
        script_content = """@echo off
REM Auto-generated Windows driver installer
REM Generated by Universal MultiBoot Wrapper

echo ============================================
echo Universal MultiBoot - Driver Installation
echo ============================================
echo.

"""
        for driver in drivers:
            if driver.suffix == '.exe':
                # Executable driver installer
                script_content += f'echo Installing {driver.name}...\n'
                script_content += f'"{driver}" /S /v/qn\n'
                script_content += 'echo.\n'
            elif driver.suffix == '.inf':
                # INF driver file
                script_content += f'echo Installing {driver.name}...\n'
                script_content += f'pnputil /add-driver "{driver}" /install\n'
                script_content += 'echo.\n'
        
        script_content += """
echo.
echo ============================================
echo Driver installation complete!
echo System will reboot in 10 seconds...
echo ============================================
timeout /t 10
shutdown /r /t 0
"""
        
        return script_content
    
    def inject_windows_drivers(self, computer_type, windows_mount_point=None):
        """Main injection function"""
        print("=" * 60)
        print("🪟 Windows Driver Injector")
        print("=" * 60)
        
        print(f"\n💻 Computer Type: {computer_type}")
        
        # Get required drivers
        required, archive_path = self.get_required_drivers(computer_type)
        print(f"\n📋 Required Drivers: {len(required)}")
        for driver in required:
            print(f"   - {driver}")
        
        # Find drivers in archive
        found = self.find_drivers_in_archive(archive_path)
        print(f"\n✅ Found in Archive: {len(found)} files")
        
        if not found:
            print("⚠️  No drivers in archive yet!")
            print(f"   Add drivers to: {self.archive_dir / archive_path}")
            return False
        
        # Show what we found
        print("\n📦 Available Drivers:")
        for driver in found[:10]:
            print(f"   - {driver.name}")
        if len(found) > 10:
            print(f"   ... and {len(found)-10} more")
        
        # If Windows mount point provided, create install script
        if windows_mount_point:
            mount_path = Path(windows_mount_point)
            if not mount_path.exists():
                print(f"\n❌ Windows mount point not found: {windows_mount_point}")
                return False
            
            print(f"\n🔧 Creating driver install script...")
            script_content = self.create_driver_install_script(found, mount_path)
            
            # Save to Windows partition
            script_path = mount_path / "install_drivers.bat"
            script_path.write_text(script_content)
            print(f"✅ Script created: {script_path}")
            
            # Copy drivers to Windows partition
            drivers_dir = mount_path / "UniversalDrivers"
            drivers_dir.mkdir(exist_ok=True)
            
            print(f"\n📥 Copying drivers to Windows partition...")
            for driver in found:
                dest = drivers_dir / driver.name
                shutil.copy2(driver, dest)
                print(f"   ✅ {driver.name}")
            
            print(f"\n✅ Drivers copied to: {drivers_dir}")
            
            print("\n" + "=" * 60)
            print("📝 Post-Boot Instructions:")
            print("=" * 60)
            print("1. Boot into Windows")
            print(f"2. Run: {script_path}")
            print("3. Drivers will install automatically")
            print("4. System will reboot")
            print("=" * 60)
        else:
            print("\n💡 Drivers ready in archive")
            print("   Mount Windows partition and run again with mount point")
        
        return True

def main():
    """Test the injector"""
    injector = WindowsInjector()
    
    # Detect computer type
    computer_type = injector.hardware_profile.get('platform', 'INTEL_PC')
    if computer_type == 'Intel':
        computer_type = 'INTEL_PC'
    elif computer_type == 'AMD':
        computer_type = 'AMD_PC'
    
    # Run injection (without mount point for now)
    injector.inject_windows_drivers(computer_type)

if __name__ == "__main__":
    main()
